# Generated by Django 5.2.1 on 2025-06-03 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Команда", "verbose_name_plural": "Команды"},
        ),
        migrations.AddField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание команды"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники команды",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название команды"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор команды",
            ),
        ),
    ]
