# Generated by Django 5.2.1 on 2025-06-04 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={
                "ordering": ["-date"],
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата встречи"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание встречи"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время окончания встречи"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор встречи",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                related_name="meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники встречи",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время начала встречи"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название встречи"
            ),
        ),
    ]
