# Generated by Django 5.2.1 on 2025-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_alter_meeting_options_meeting_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateField(verbose_name="Дата встречи"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="end_time",
            field=models.TimeField(verbose_name="Время окончания встречи"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(verbose_name="Время начала встречи"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название встречи"),
        ),
    ]
