# Generated by Django 5.2.1 on 2025-06-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meeting_date_alter_meeting_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="end_time",
            field=models.TimeField(
                db_index=True, verbose_name="Время окончания встречи"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(db_index=True, verbose_name="Время начала встречи"),
        ),
    ]
