# Generated by Django 5.2.1 on 2025-06-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь, который создал задачу",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                ],
                default="open",
                max_length=20,
                verbose_name="Статус задачи",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_performer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performer_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель которому назначена задача",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название задачи"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                        verbose_name="Задача, к которой относится комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
    ]
